export const sections = [
  {
    id: "oncology",
    label: "Oncology",
    color: "#e05c5c",
    conditions: [
      { id: "o1", name: "Breast cancer", yield: 3 },
      { id: "o2", name: "Lung cancer", yield: 3 },
      { id: "o3", name: "Lymphoma", yield: 2 },
      { id: "o4", name: "Melanoma", yield: 3 },
      { id: "o5", name: "Prostate cancer", yield: 3 },
      { id: "o6", name: "Colorectal cancer", yield: 3 },
    ],
  },
  {
    id: "ed_cardio",
    label: "ED – Cardiovascular",
    color: "#c0392b",
    conditions: [
      { id: "ec1", name: "Cardiac arrest", yield: 3 },
      { id: "ec2", name: "Arrhythmias", yield: 3 },
      { id: "ec3", name: "Acute LVF", yield: 3 },
      { id: "ec4", name: "Pericarditis / myocarditis", yield: 2 },
      { id: "ec5", name: "Acute limb ischaemia", yield: 2 },
      { id: "ec6", name: "Aortic aneurysm", yield: 2 },
      { id: "ec7", name: "Aortic dissection", yield: 2 },
      { id: "ec8", name: "DVT", yield: 2 },
      { id: "ec9", name: "Malignant hypertension", yield: 2 },
      { id: "ec10", name: "BRUE", yield: 2 },
    ],
  },
  {
    id: "ed_resp",
    label: "ED – Respiratory",
    color: "#2980b9",
    conditions: [
      { id: "er1", name: "Inhaled foreign body / aspiration", yield: 2 },
      { id: "er2", name: "Acute asthma", yield: 3 },
      { id: "er3", name: "Pneumothorax", yield: 3 },
      { id: "er4", name: "Pneumonia", yield: 3 },
      { id: "er5", name: "Exacerbation of COPD", yield: 3 },
      { id: "er6", name: "Pulmonary embolism", yield: 3 },
      { id: "er7", name: "Bronchiolitis", yield: 2 },
      { id: "er8", name: "Croup", yield: 2 },
    ],
  },
  {
    id: "ed_neuro",
    label: "ED – Neurology",
    color: "#8e44ad",
    conditions: [
      { id: "en1", name: "Stroke and stroke mimics", yield: 3 },
      { id: "en2", name: "Spinal cord / cauda lesion", yield: 2 },
      { id: "en3", name: "Migraine", yield: 3 },
      { id: "en4", name: "Intraparenchymal / SAH / subdural / extradural haemorrhage", yield: 2 },
      { id: "en5", name: "Vertigo (central, BPPV, vestibulopathies)", yield: 2 },
      { id: "en6", name: "CNS infections", yield: 2 },
    ],
  },
  {
    id: "ed_mh",
    label: "ED – Mental Health",
    color: "#16a085",
    conditions: [
      { id: "mh1", name: "Acute psychosis", yield: 2 },
      { id: "mh2", name: "Acute mania", yield: 2 },
      { id: "mh3", name: "Acute anxiety", yield: 2 },
      { id: "mh4", name: "Personality disorders", yield: 2 },
      { id: "mh5", name: "Depression", yield: 2 },
      { id: "mh6", name: "Somatisation disorders", yield: 2 },
    ],
  },
  {
    id: "ed_gi",
    label: "ED – Gastrointestinal",
    color: "#d35400",
    conditions: [
      { id: "egi1", name: "Liver failure", yield: 2 },
      { id: "egi2", name: "Ischaemic bowel", yield: 2 },
      { id: "egi3", name: "Bowel obstruction", yield: 2 },
      { id: "egi4", name: "Gastroenteritis", yield: 2 },
      { id: "egi5", name: "Peritonitis", yield: 2 },
    ],
  },
  {
    id: "ed_renal",
    label: "ED – Urinary / Renal / Fluids",
    color: "#1abc9c",
    conditions: [
      { id: "eur1", name: "Acute kidney injury", yield: 3 },
      { id: "eur2", name: "Acute urinary retention", yield: 2 },
      { id: "eur3", name: "Ureteric colic", yield: 2 },
      { id: "eur4", name: "Urinary infections", yield: 3 },
      { id: "eur5", name: "Fluid and electrolyte disturbances / dehydration", yield: 3 },
      { id: "eur6", name: "Hypoglycaemia", yield: 2 },
      { id: "eur7", name: "Hyperglycaemia", yield: 2 },
    ],
  },
  {
    id: "ed_haem",
    label: "ED – Haematology / Infection",
    color: "#c0392b",
    conditions: [
      { id: "ehi1", name: "Anaemia", yield: 2 },
      { id: "ehi2", name: "Febrile neutropenia", yield: 2 },
      { id: "ehi3", name: "Sepsis", yield: 3 },
      { id: "ehi4", name: "Cellulitis and soft tissue infections", yield: 2 },
      { id: "ehi5", name: "Fever of unknown source", yield: 2 },
      { id: "ehi6", name: "The unwell returned traveler", yield: 2 },
      { id: "ehi7", name: "Clotting disorders", yield: 2 },
      { id: "ehi8", name: "Anaphylaxis and acute allergic reactions", yield: 3 },
    ],
  },
  {
    id: "ed_ent",
    label: "ED – ENT / Ophth / Rheum / Derm",
    color: "#27ae60",
    conditions: [
      { id: "eent1", name: "Epistaxis, ear pain, sore throat", yield: 2 },
      { id: "eent2", name: "ENT foreign bodies", yield: 2 },
      { id: "eent3", name: "Dental pain and injuries", yield: 2 },
      { id: "eent4", name: "Acute visual loss", yield: 2 },
      { id: "eent5", name: "Acute eye pain, redness or trauma", yield: 2 },
      { id: "eent6", name: "Acute monoarthropathy", yield: 2 },
      { id: "eent7", name: "Common acute rashes", yield: 2 },
      { id: "eent8", name: "Rare but life-threatening rashes", yield: 2 },
    ],
  },
  {
    id: "ed_tox",
    label: "ED – Toxicology / Environmental",
    color: "#7f8c8d",
    conditions: [
      { id: "etox1", name: "Spider, snake and marine envenomation", yield: 2 },
      { id: "etox2", name: "Electrical injuries", yield: 2 },
      { id: "etox3", name: "Temperature-related conditions", yield: 2 },
      { id: "etox4", name: "Submersion", yield: 2 },
      { id: "etox5", name: "Common drug intoxication and withdrawal", yield: 2 },
    ],
  },
  {
    id: "ed_trauma",
    label: "ED – Trauma",
    color: "#95a5a6",
    conditions: [
      { id: "etr1", name: "Spinal, head, facial, truncal, multiple injuries", yield: 2 },
      { id: "etr2", name: "Common acute bone and joint injuries of the limbs", yield: 2 },
      { id: "etr3", name: "Soft tissue injuries", yield: 2 },
      { id: "etr4", name: "Burns", yield: 2 },
    ],
  },
  {
    id: "im_blood",
    label: "Internal Med – Blood",
    color: "#e74c3c",
    conditions: [
      { id: "imb1", name: "Anaemia", yield: 3 },
      { id: "imb2", name: "Acquired coagulopathies (e.g. liver disease)", yield: 2 },
      { id: "imb3", name: "Haematinic deficiency: Iron, B12 and Folate", yield: 2 },
      { id: "imb4", name: "Thrombophilia (stroke / DVT / PE risk)", yield: 1 },
    ],
  },
  {
    id: "im_cardio",
    label: "Internal Med – Cardiovascular",
    color: "#c0392b",
    conditions: [
      { id: "imc1", name: "Acute pulmonary oedema", yield: 2 },
      { id: "imc2", name: "Vascular complications of diabetes", yield: 2 },
      { id: "imc3", name: "Cardiac arrest", yield: 2 },
      { id: "imc4", name: "DVT", yield: 2 },
      { id: "imc5", name: "Peripheral arterial disease", yield: 2 },
      { id: "imc6", name: "Major cardiac arrhythmias and conduction defects", yield: 2 },
      { id: "imc7", name: "Infective endocarditis", yield: 2 },
      { id: "imc8", name: "Heart valve disease", yield: 2 },
      { id: "imc9", name: "Circulatory shock / hypotension", yield: 3 },
      { id: "imc10", name: "Dyslipidaemia", yield: 3 },
      { id: "imc11", name: "Essential hypertension", yield: 3 },
      { id: "imc12", name: "Ischaemic heart disease and ACS", yield: 3 },
      { id: "imc13", name: "Heart failure", yield: 3 },
    ],
  },
  {
    id: "im_endo",
    label: "Internal Med – Endocrine",
    color: "#f39c12",
    conditions: [
      { id: "ime1", name: "Hypoglycaemia", yield: 2 },
      { id: "ime2", name: "Hypoadrenalism – acute and chronic", yield: 2 },
      { id: "ime3", name: "Hyperkalaemia / Hypokalaemia", yield: 2 },
      { id: "ime4", name: "Hypernatraemia / Hyponatraemia", yield: 2 },
      { id: "ime5", name: "Hypercalcaemia / Hypocalcaemia", yield: 1 },
      { id: "ime6", name: "Hyperglycaemic hyperosmolar state", yield: 1 },
      { id: "ime7", name: "Diabetic ketoacidosis", yield: 2 },
      { id: "ime8", name: "Type 1 Diabetes / Type 2 Diabetes", yield: 3 },
      { id: "ime9", name: "Thyroid dysfunction – hyper and hypo", yield: 2 },
    ],
  },
  {
    id: "im_gastro",
    label: "Internal Med – Gastroenterology",
    color: "#e67e22",
    conditions: [
      { id: "img1", name: "Acute infectious diarrhoea / food poisoning", yield: 3 },
      { id: "img2", name: "Obesity and overweight", yield: 3 },
      { id: "img3", name: "Coeliac disease", yield: 2 },
      { id: "img4", name: "Dehydration", yield: 2 },
      { id: "img5", name: "Simple constipation / faecal impaction", yield: 2 },
      { id: "img6", name: "Antibiotic-associated diarrhoea", yield: 2 },
      { id: "img7", name: "Irritable bowel syndrome", yield: 2 },
      { id: "img8", name: "Metabolic syndrome", yield: 2 },
      { id: "img9", name: "Hepatitis: viral / autoimmune / drug-induced", yield: 2 },
      { id: "img10", name: "Acute liver failure", yield: 2 },
      { id: "img11", name: "Fatty liver disease", yield: 2 },
      { id: "img12", name: "Alcoholic liver disease", yield: 2 },
      { id: "img13", name: "Liver tumours / metastases", yield: 2 },
      { id: "img14", name: "Cirrhosis", yield: 2 },
      { id: "img15", name: "Peptic ulcer disease", yield: 2 },
      { id: "img16", name: "Inflammatory bowel disease", yield: 2 },
      { id: "img17", name: "Colorectal cancer", yield: 3 },
      { id: "img18", name: "GORD / oesophagitis / gastritis", yield: 3 },
    ],
  },
  {
    id: "im_renal",
    label: "Internal Med – Genitourinary",
    color: "#1abc9c",
    conditions: [
      { id: "imr1", name: "Difficulty passing urine – frequency / dysuria", yield: 3 },
      { id: "imr2", name: "Urinary tract obstruction", yield: 2 },
      { id: "imr3", name: "Urinary incontinence", yield: 2 },
      { id: "imr4", name: "Acute kidney injury", yield: 2 },
      { id: "imr5", name: "Diabetic nephropathy", yield: 2 },
      { id: "imr6", name: "Hypertensive renal disease", yield: 2 },
      { id: "imr7", name: "Nephrotic / nephritic syndrome / glomerulonephritis", yield: 1 },
      { id: "imr8", name: "Urinary tract infection", yield: 3 },
      { id: "imr9", name: "Chronic kidney disease", yield: 3 },
    ],
  },
  {
    id: "im_immune",
    label: "Internal Med – Immune & Infection",
    color: "#2ecc71",
    conditions: [
      { id: "imi1", name: "Anaphylaxis", yield: 3 },
      { id: "imi2", name: "Hospital acquired infections", yield: 2 },
      { id: "imi3", name: "Infection in the immunocompromised", yield: 2 },
      { id: "imi4", name: "Septicaemia", yield: 2 },
      { id: "imi5", name: "HIV", yield: 2 },
      { id: "imi6", name: "Fever in returned traveller", yield: 2 },
      { id: "imi7", name: "Drug allergy", yield: 2 },
      { id: "imi8", name: "Angioedema / urticaria", yield: 2 },
    ],
  },
  {
    id: "im_neuro",
    label: "Internal Med – Neurology",
    color: "#9b59b6",
    conditions: [
      { id: "imn1", name: "Epilepsy", yield: 3 },
      { id: "imn2", name: "Alzheimer's disease / dementia", yield: 3 },
      { id: "imn3", name: "Delirium", yield: 3 },
      { id: "imn4", name: "Stroke and TIA", yield: 3 },
      { id: "imn5", name: "Migraine / headaches", yield: 3 },
      { id: "imn6", name: "Meningitis", yield: 3 },
      { id: "imn7", name: "Parkinson's disease", yield: 2 },
      { id: "imn8", name: "Multiple sclerosis", yield: 2 },
      { id: "imn9", name: "Spinal cord compression", yield: 2 },
      { id: "imn10", name: "Intracranial haemorrhage (extradural/subdural/SAH)", yield: 2 },
    ],
  },
  {
    id: "im_resp",
    label: "Internal Med – Respiratory",
    color: "#3498db",
    conditions: [
      { id: "imrsp1", name: "Asthma", yield: 3 },
      { id: "imrsp2", name: "COPD", yield: 3 },
      { id: "imrsp3", name: "Pneumonia", yield: 3 },
      { id: "imrsp4", name: "Respiratory failure", yield: 3 },
      { id: "imrsp5", name: "Lung cancer / nodule evaluation", yield: 3 },
      { id: "imrsp6", name: "Pulmonary embolism", yield: 3 },
      { id: "imrsp7", name: "Aspiration", yield: 2 },
      { id: "imrsp8", name: "Pneumothorax", yield: 2 },
      { id: "imrsp9", name: "Obstructive sleep apnoea", yield: 2 },
      { id: "imrsp10", name: "Bronchiectasis", yield: 2 },
      { id: "imrsp11", name: "Pleural effusion", yield: 2 },
      { id: "imrsp12", name: "Pleural empyema", yield: 2 },
      { id: "imrsp13", name: "Idiopathic pulmonary fibrosis / ILD", yield: 2 },
    ],
  },
  {
    id: "im_tox",
    label: "Internal Med – Toxicology",
    color: "#7f8c8d",
    conditions: [
      { id: "imt1", name: "Alcohol intoxication, withdrawal, dependence", yield: 3 },
      { id: "imt2", name: "Tobacco smoking and sequelae", yield: 3 },
      { id: "imt3", name: "Warfarin and new anticoagulant agents", yield: 2 },
      { id: "imt4", name: "Paracetamol toxicity", yield: 2 },
      { id: "imt5", name: "Opioid toxicity and withdrawal", yield: 2 },
      { id: "imt6", name: "Amphetamine dependence", yield: 2 },
    ],
  },
  {
    id: "im_misc",
    label: "Internal Med – General",
    color: "#95a5a6",
    conditions: [
      { id: "imm1", name: "Fever", yield: 3 },
      { id: "imm2", name: "Fatigue", yield: 2 },
      { id: "imm3", name: "Weight gain / loss", yield: 2 },
    ],
  },
  {
    id: "anaesthetics",
    label: "Anaesthetics",
    color: "#2c3e50",
    conditions: [
      { id: "an1", name: "Perioperative fluids", yield: 2 },
      { id: "an2", name: "Anaphylaxis", yield: 3 },
      { id: "an3", name: "Septicaemia and septic shock", yield: 2 },
      { id: "an4", name: "Haemorrhagic shock", yield: 2 },
      { id: "an5", name: "Pre-assessment and comorbidities", yield: 2 },
      { id: "an6", name: "Difficult airway", yield: 2 },
      { id: "an7", name: "Residual NM block", yield: 2 },
      { id: "an8", name: "Pain management", yield: 2 },
      { id: "an9", name: "Fluid/electrolyte/acid-base disorders", yield: 2 },
      { id: "an10", name: "Respiratory failure", yield: 2 },
      { id: "an11", name: "PONV", yield: 2 },
      { id: "an12", name: "Shock", yield: 2 },
      { id: "an13", name: "Fasting guidelines", yield: 2 },
      { id: "an14", name: "Preoperative fasting", yield: 2 },
      { id: "an15", name: "Preoxygenation", yield: 2 },
      { id: "an16", name: "Induction of anaesthesia", yield: 2 },
    ],
  },
  {
    id: "ent",
    label: "ENT",
    color: "#27ae60",
    conditions: [
      { id: "ent1", name: "Epiglottitis", yield: 2 },
      { id: "ent2", name: "Perforated tympanic membrane", yield: 2 },
      { id: "ent3", name: "Orbital and periorbital cellulitis", yield: 2 },
      { id: "ent4", name: "Epistaxis", yield: 2 },
      { id: "ent5", name: "Sinusitis", yield: 2 },
      { id: "ent6", name: "Otitis media", yield: 3 },
      { id: "ent7", name: "Tonsillitis and pharyngitis", yield: 3 },
      { id: "ent8", name: "Hearing loss", yield: 3 },
      { id: "ent9", name: "Vertigo", yield: 2 },
      { id: "ent10", name: "Tinnitus", yield: 2 },
      { id: "ent11", name: "Foreign body (ENT)", yield: 2 },
      { id: "ent12", name: "OSA", yield: 2 },
      { id: "ent13", name: "Facial pain", yield: 2 },
      { id: "ent14", name: "Stridor and airway obstruction", yield: 2 },
      { id: "ent15", name: "Head and neck mass", yield: 2 },
      { id: "ent16", name: "Allergic rhinitis", yield: 2 },
      { id: "ent17", name: "Hoarseness", yield: 2 },
      { id: "ent18", name: "Dysphagia", yield: 2 },
    ],
  },
  {
    id: "surgery",
    label: "Surgery",
    color: "#c0392b",
    conditions: [
      { id: "sx1", name: "Aortic dissection", yield: 2 },
      { id: "sx2", name: "Perianal disease", yield: 2 },
      { id: "sx3", name: "Venous skin disease and ulcers", yield: 2 },
      { id: "sx4", name: "Drug intoxication / OD", yield: 2 },
      { id: "sx5", name: "Pelvic fractures", yield: 2 },
      { id: "sx6", name: "Urinary retention", yield: 2 },
      { id: "sx7", name: "Testicular torsion", yield: 2 },
      { id: "sx8", name: "Skin and soft tissue trauma", yield: 3 },
      { id: "sx9", name: "Peritonitis", yield: 2 },
      { id: "sx10", name: "Head injuries", yield: 3 },
      { id: "sx11", name: "Liver tumours", yield: 2 },
      { id: "sx12", name: "Alcoholic liver disease", yield: 2 },
      { id: "sx13", name: "Ischaemic bowel", yield: 2 },
      { id: "sx14", name: "Prostate cancer", yield: 3 },
      { id: "sx15", name: "Appendicitis", yield: 2 },
      { id: "sx16", name: "Abdominal wall hernias", yield: 2 },
      { id: "sx17", name: "Melanoma", yield: 3 },
      { id: "sx18", name: "Inflammatory bowel disease", yield: 2 },
      { id: "sx19", name: "Diverticular disease", yield: 2 },
      { id: "sx20", name: "Peptic ulcer disease", yield: 2 },
      { id: "sx21", name: "Acute and chronic pancreatitis", yield: 2 },
      { id: "sx22", name: "Colorectal cancer", yield: 3 },
      { id: "sx23", name: "Gallstone disease", yield: 3 },
      { id: "sx24", name: "Acute cholangitis", yield: 3 },
      { id: "sx25", name: "GORD", yield: 3 },
    ],
  },
];

export const STORAGE_KEY = "core_conditions_progress_v1";
